[server]
enableStaticServing = false
runOnSave = true
maxUploadSize = 400
maxMessageSize = 400
[theme]
base = 'dark'
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"
